### ISSUE TITLE
Tag/Publish releases of PyCIEMSS library

### ISSUE THREAD

**Issue by fivegrant** [DARPA-ASKEM/pyciemss-service#35]
Currently, we have to specify the exact commit hash for the PyCIEMSS version we want to install. This is confusing from the dev perspective and could cause issues with updates down the line. PyCIEMSS (and ideally MIRA) need to start versioning so we can declare definitely if the system works or not.

tl;dr: tags are less obstuse than hashes. also, the libs we depend on should build as deterministically as possible. 

See [this discussion](https://github.com/DARPA-ASKEM/pyciemss-service/pull/34#discussion_r1291725058).

## TODO:
1. [x] https://github.com/ciemss/pyciemss/issues/344
1. [ ] (Optional?) Freeze MIRA release in PyCIEMSS lib
1. [x] Start using the specific releases in our poe task.
