### ISSUE TITLE
Implement InterventionPolicy API

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/pyciemss-service#97]
Waiting for TA3 design to be finalized.

With the added support of intervention in pyciemms, update the API endpoints to accept _InterventionPolicies_ with a request.

```
Will update essentially convert_to_static_interventions 
And have pyciemss-service read a InterventionPolicyID
All parsing will be done in pyciemss-service

```

**tasks**
- [ ] Update the models operations `simulate.py` to handle **static** intervention policies
- [ ] Update the models operations `simulate.py` to handle **dynamic** intervention policies
- [ ] Update the models operations `calibrate.py` to handle **static** intervention policies
- [ ] Update the models operations `calibrate.py` to handle **dynamic** intervention policies
- [ ] Update the models operations `optimize.py` to handle **static** intervention policies
